//Melissa Iori
//This script generator takes in as input files generated by graphFileGenerator.
//It can output SQL files or G* script files.

//File module
var fs = require('fs');

//If not enough arguments, exit
//User must include the name of a valid input file, whether they want sql or gstar output, and the name of an output file.
if(process.argv.length < 5){
	console.log("Usage: node graphScriptGeneratorDual input-file output-sql-file output-gstar-file");
	process.exit(1);
}

//Read the file contents
graph = fs.readFileSync(process.argv[2]);

//Split at separator into vertex list and edge list
graphComponents = graph.toString().split("***");
nodesString = graphComponents[0];
edgesString = graphComponents[1];

//Create vertex array
nodes = nodesString.split("\n");
//Create edge array
edges = edgesString.split("\n");

//This is the string to be written as the final output
outString = "";

	
	//Create tables and start INSERT statement
	sqlString = "";
	sqlString += "INSERT INTO Vertices (id) VALUES \n"

	//For each node, if valid, write it into SQL
	for(var i = 0; i < nodes.length; i++){
		nodes[i] = nodes[i].substring(0, nodes[i].length-1);
		if(nodes[i].trim() !== ""){
			if(i == nodes.length-1){
				sqlString += "(" + nodes[i] + ")";
			}
			else{
				sqlString += "(" + nodes[i] + "),\n";
			}
		}
	}

	//Trim off excess and add semicolon
	sqlString = sqlString.substring(0, sqlString.length-2);
	sqlString += ";";

	//INSERT into Edges...
	sqlString += "\nINSERT INTO Edges (vertexFrom, vertexTo) VALUES ";

	//For each edge, if valid, write into SQL.
	for(var j = 0; j < edges.length; j++){
			edges[j] = edges[j].substring(0, edges[j].length-1);
			if(edges[j].trim() !== ""){
					sqlString += edges[j] + "," + "\n";
			}
	}
	
	//Trim off excess and add semicolon
	sqlString = sqlString.substring(0, sqlString.length-2);
	sqlString += ";";


	gstarString = "";
	//Create vertex array
nodes = nodesString.split("\n");
//Create edge array
edges = edgesString.split("\n");

	//Write vertices
	for(var i = 0; i < nodes.length; i++){
		if(nodes[i].trim() !== ""){
			gstarString += "vertex " + nodes[i] + "\n";
		}	
	}

	//Write edges
	for(var j = 0; j < edges.length; j++){
			if(edges[j].trim() !== ""){
				edge = edges[j].substring(1,edges[j].length-2);
				edge = edge.replace(", ", " ");
				gstarString += "edge " + edge + "\n";
			}
	}

//Finally, write the formatted output to the output file and notify the user.
fs.writeFileSync(process.argv[3], sqlString);
console.log("Done, wrote to " + process.argv[3]);
fs.writeFileSync(process.argv[4], gstarString);
console.log("Done, wrote to " + process.argv[4]);